language: python

python:
  - "3.6"
  - "nightly"

env:
  # Add variables TOKEN and ID in TravisCI settings
  - DATE=2017-02-18

script:
  - ./vulncontrol.py
  - ./vulncontrol.py -t $TOKEN $ID
  - ./vulncontrol.py -d $DATE ; [[ $? -eq 1 ]]
  - ./vulncontrol.py -t $TOKEN $ID -d $DATE ; [[ $? -eq 2 ]]
  - ./vulncontrol.py -t 111:ABC 123 -d $DATE ; [[ $? -eq 3 ]]
