name: Vulncontrol

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Linter
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Tests
      env:
        DATE: "2018-06-05"
      run: |
        echo "Test withour sending message:"
        ./vulncontrol.py
        echo "Test with TG credentials:"
        ./vulncontrol.py -t ${{ secrets.TOKEN }} ${{ secrets.ID }}
        echo "Test with date:"
        ./vulncontrol.py -d ${DATE} ; [[ $? -eq 1 ]]
        echo "Test with TG credentials and date:"
        ./vulncontrol.py -t ${{ secrets.TOKEN }} ${{ secrets.ID }} -d ${DATE} ; [[ $? -eq 2 ]]
        echo "Test with incorrect TG credentials:"
        ./vulncontrol.py -t 111:ABC 123 -d ${DATE} ; [[ $? -eq 3 ]]
